import { BaseModel } from './base.js'

/**
 * @typedef {BaseModelOptions & object} ScenarioOptions
 * @property {string} [id] - Scenario ID
 * @property {string} [name] - Name, shown on the scenarios page
 * @property {string} [description] - What this scenario sets up and why
 * @property {string} [startUrl] - Best page to land on for a demo of this scenario
 * @property {Array<ScenarioLink>} [links] - Direct links to the key entities this scenario created
 */

/**
 * @typedef {object} ScenarioLink
 * @property {string} label - What this links to
 * @property {string} href - URL to link to
 */

/**
 * A pre-built demo/test scenario, generated by `npm run create-data` (see `lib/scenarios/`).
 * Read-only from the app's point of view - nothing here is ever created or edited at runtime.
 *
 * @class Scenario
 */
export class Scenario extends BaseModel {
  static contextKey = 'scenarios'
  static identifierKey = 'id'
  static ns = 'scenario'

  /**
   * @param {ScenarioOptions} options - Options
   * @param {object} [context] - Context
   */
  constructor(options, context) {
    super(options, context)

    this.id = options?.id
    this.name = options?.name
    this.description = options?.description
    this.startUrl = options?.startUrl
    this.links = options?.links || []
  }
}
